version: '3.8'

services:
  mage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6789:6789"
    volumes:
      - ./bike_demand_prediction:/app/bike_demand_prediction
      - ./mage_data:/app/mage_data
    environment:
      - MAGE_PROJECT_PATH=/app/bike_demand_prediction

  mlflow:
    image: bitnami/mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns  # Зберігання артефактів MLflow
